### ISSUE TITLE
Navbar doesn't go to top of page at the right time

### ISSUE THREAD

**Issue by kvizdos** [TheRealmOfTheGeek/TheRealmOfTheGeek.github.io#20]

**Comment by farmerau** [comment]
What is the right time?

**Comment by kvizdos** [comment]
@farmerau right time?

**Comment by farmerau** [comment]
This issue is titled, "Navbar doesn't go to top of page at the right time "

**Comment by kvizdos** [comment]
Ah, sorry, I read the title as this being referred to the White gap.. 

It should just follow the top of the browser as the navbar hits the top.. 

This is how it is now:
![Top](https://i.imgur.com/FNxVNjG.png)

and it should wait a little longer until the URL bar (?) hits the position of the navbar, and then start scrolling
![How it should be](https://i.imgur.com/H4vFbeJ.png)

**Comment by kvizdos** [comment]
When we fixed #21 it fixed this
