### ISSUE TITLE
Huge white gap at the top of the page

### ISSUE THREAD

**Issue by kvizdos** [TheRealmOfTheGeek/TheRealmOfTheGeek.github.io#21]
a huge white gap is at the top of the page that isn't supposed to be there, fixing this may also fix #20
Example below. 
![White gap](https://i.imgur.com/T8KYRTW.png)

**Comment by farmerau** [comment]
Could you provide browser information / webpage / screenshots?

**Comment by kvizdos** [comment]
@farmerau Updated the issue.

**Comment by Jack-Rouleau** [comment]
Got a fix ready to push, don't seem to have permission to push to branch.

**Comment by kvizdos** [comment]
@Jack-Rouleau I'll check and update permissions now. Thanks for telling me!

**Comment by kvizdos** [comment]
@Jack-Rouleau can you create a pull request for it?

**Comment by farmerau** [comment]
Looks like Chrome. Windows user?

Also, what's your screen resolution? Still can't reproduce here.

**Comment by kvizdos** [comment]
Hmm. I've now tried on my main PC (Windows 10, Chrome), my laptop (Mac OSX Sierra, Safari & Chrome) and my S7 Edge (Chrome)

## Mac (Safari): 
![Mac](https://i.imgur.com/JzEuBuA.png)

## S7 Edge (Chrome):
![S7 Edge](https://i.imgur.com/SxA4Xzb.png)

**Comment by Jack-Rouleau** [comment]
It's the googleads javascript that's failling, either remove the snippet in the header file or fix whatever is making it fail.  Your keys might be invalid.

**Comment by kvizdos** [comment]
Oh, interesting. Do you want to submit a pull request for Hacktoberfest?

**Comment by kvizdos** [comment]
And I'm guessing @farmerau, you're using AdBlocker, and that's why you're not seeing the white space?

**Comment by kvizdos** [comment]
As I suspected, deleting that bit of code with inspect element, it fixes #20

**Comment by Jack-Rouleau** [comment]
Yeah would have pushed something earlier but I keep getting an error for some reason

**Comment by kvizdos** [comment]
And what about a pull request? Unauthorized users can't push, but they can open pull requests @Jack-Rouleau

**Comment by Jack-Rouleau** [comment]
I'd need to be able to push to a branch to be able to create a pull request :P

**Comment by kvizdos** [comment]
Any error code? Screenshot?

**Comment by farmerau** [comment]
Ah, that makes sense. Sorry about that.

**Comment by Jack-Rouleau** [comment]
![image](https://user-images.githubusercontent.com/10734288/31156533-edda7d82-a882-11e7-92c2-47446b92be30.png)

If others are able to push their branches I probably just screwed up my SSH configs on this computer at some point haha

**Comment by farmerau** [comment]
@Jack-Rouleau I think it's relatively common to fork the repo, commit your changes to the forked repo and then submit a PR. Not sure, though.

**Comment by kvizdos** [comment]
@Jack-Rouleau Did you set the remote and everything?

**Comment by gmemstr** [comment]
You need to fork this repository, then change the remote as described [here](https://help.github.com/articles/changing-a-remote-s-url/). You currently have it pointing to this repository, which you are not allowed to push to. Once you have pushed changes to your own repository, you will see a button to create a new pull request.

**Comment by Jack-Rouleau** [comment]
@gmemstr Thanks!  Never worked with repositories I didn't have push permission to.

**Comment by kvizdos** [comment]
Oh, thanks @gmemstr for the quick how-to! I have yet to do a pull request, so I didn't know how to do it, thanks for telling us!

**Comment by gmemstr** [comment]
I should mention the pull request button will be branch rollout beneath the repository stats (commits etc) on your own repository.

**Comment by kvizdos** [comment]
Good to know

**Comment by kvizdos** [comment]
You doing good, @Jack-Rouleau?
