### ISSUE TITLE
[Bootstrap] Mobile Nav Bar Burger doesn't show up

### ISSUE THREAD

**Issue by kvizdos** [TheRealmOfTheGeek/TheRealmOfTheGeek.github.io#23]
When viewing on a mobile device, the navbar burger doesn't show up.

**Comment by farmerau** [comment]
Android or iOS? What model of phone? Seems to be showing up for me, once you scroll down the page. Just like the regular navigation: ![screenshot](http://d.pr/i/ZzWMMC.png)

**Comment by kvizdos** [comment]
I tried it on my S7 Edge, I guess its a screen size issue? Maybe the curved edges make it too wide for Bootstraps navigation system? Hmm. I'll close the issue, as testing it now with my mom's and brothers' phone works fine.
