### ISSUE TITLE
navbar buttons go a little to far down

### ISSUE THREAD

**Issue by kvizdos** [TheRealmOfTheGeek/TheRealmOfTheGeek.github.io#24]
When you click the "About" button, it the section title is blocked by the navbar

**Comment by chasingSublimity** [comment]
Heya. 👋 I'll take a look.

**Comment by chasingSublimity** [comment]
So it looks like the issue is actually in your javascript. If you click the about me button more than once, the page behaves as expected after the initial click. lemme do some more digging.

**Comment by kvizdos** [comment]
Huh.. checking the site now, it seems to have fixed itself? I guess fixing #21 also fixed this... interesting.. I'm not sure why it'd fix it, but thats the only file we've changed..

**Comment by chasingSublimity** [comment]
I'm still seeing it on my end, but only when I navigate to https://therotg.com/, not https://therotg.com/#about . 🤔

**Comment by kvizdos** [comment]
Ah, I'm seeing that as well now too.. this is a strange issue.

**Comment by chasingSublimity** [comment]
I think it has something to do with the `affix` class that gets applied to the nav bar. Where are you handling that in the code?

**Comment by kvizdos** [comment]
I'm getting that from Bootstrap

**Comment by chasingSublimity** [comment]
Ah. What version?

**Comment by kvizdos** [comment]
Bootstrap v3.3.7

**Comment by kvizdos** [comment]
just for an update, I'm going to head to bed. I'll respond to any questions in the morning when I wake up. Thanks for trying to figure this out, and sorry I need to tap out for the night

**Comment by sagarvd01** [comment]
Got the problem and it is the intended behaviour. leave a comment if you need more details.

**Comment by kvizdos** [comment]
@sagarvd01 is there any way to make it go higher?

**Comment by finches** [comment]
For what it's worth, if you replace this line in nav.js:
`window.location.hash = hash`

With this one:
`history.pushState(null, null, hash);`

It should work like I think you want it to. Can open a PR if you want, but know someone else is working on this.

**Comment by kvizdos** [comment]
Let's see if @chasingSublimity finds a fix first, if he doesn't find a fix by the end of the night, go ahead and make a push request ;)

**Comment by sagarvd01** [comment]
@kvizdos the `#` value in url will scroll upto the element with that id. Since you're navbar's position is `fixed`, it will stay independent to all other elements on that page. So, the page scrolls to make the heading come to top of page but the navbar is hiding that.

**Comment by kvizdos** [comment]
Closed by pull request #31
