### ISSUE TITLE
Make the readme.md better

### ISSUE THREAD

**Issue by kvizdos** [TheRealmOfTheGeek/TheRealmOfTheGeek.github.io#26]
Maybe add some pictures, more details, and other fun things to the readme.md?

**Comment by aubuchcl** [comment]
I'd like to take this.  New to open source contributions, but as I understand I would just clone, make changes, then make pull request.

**Comment by kvizdos** [comment]
To get started, you'd fork the project, and after you've made the changes and committed it to your project, go to the version of this repo thats on your portfolio and go to Pull requests and submit it :)

**Comment by aubuchcl** [comment]
Thanks I'll get to it tonight.

**Comment by kvizdos** [comment]
Alright, no rush, thanks for contributing! I'll be heading to bed soon, so I may accept the pull request tomorrow (if you get it done tonight)

**Comment by aubuchcl** [comment]
Pull request is in!  Hope its what you were looking for.
