### ISSUE TITLE
Make the "passing" label auto update

### ISSUE THREAD

**Issue by kvizdos** [TheRealmOfTheGeek/TheRealmOfTheGeek.github.io#27]
Make the "passing" label in the readme to auto-update if the build fails, etc

**Comment by gmemstr** [comment]
What are you currently using to build the project? We could hook this up to a CI PaaS but we need to know how you build the project first.

**Comment by kvizdos** [comment]
Currently, I'm not using anything to build the project. What do you recommend to build it? (Sorry, still new to building projects and testing them)

**Comment by kvizdos** [comment]
I thought github had one built in, as I keep getting emails saying there was a page build failure, I'm guessing thats from GitHub Pages' builder, but I'm sure there's something better than that.

**Comment by gmemstr** [comment]
Okay, I'll try to put what's in my head into words;

Your website is primarily PHP based, right? I'm going to guess you aren't using Github pages for your actual website, but this repository is of all the website files?

Essentially, PHP isn't a language you "build". You could technically, by visiting the pages and saving them, but that's beside the point.

**Comment by kvizdos** [comment]
Ah, so there is no real point to make the label?

**Comment by gmemstr** [comment]
Technically, no. If you were using something like Go or C++ that has to build, then yes, but with PHP not really :)

**Comment by kvizdos** [comment]
Alright, thanks for the info, I'll close this issue now :)
