### ISSUE TITLE
Website creation 

### ISSUE THREAD

**Issue by Lwazilwenkos** [TheRealmOfTheGeek/TheRealmOfTheGeek.github.io#34]
Please create webserver for me

**Comment by kvizdos** [comment]
You can get one going with a server that runs PHP :) 

Consider spinning up a LAMP server on digital ocean (referral link):
https://m.do.co/c/485af8aecc9f

How to guide:

https://www.digitalocean.com/community/tutorials/how-to-use-the-lamp-1-click-install-on-digitalocean
